// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package meteor

import (
	"io"
	"strings"
	"testing"
	"bytes"
	"reflect"
	"net/http"
	"net/http/httptest"
	"encoding/base64"
	"io/ioutil"
)

func Test_bodyProvider_ContentType(t *testing.T) {
	tests := []struct {
		name string
		p    bodyProvider
		want string
	}{
		{"generic", bodyProvider{strings.NewReader("raw body")}, ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.p.ContentType(); got != tt.want {
				t.Errorf("bodyProvider.ContentType() = %v, want %v", got, tt.want)
			}
		})
	}
}

func Test_bodyProvider_Body(t *testing.T) {
	tests := []struct {
		name    string
		p       bodyProvider
		want    io.Reader
		wantErr bool
	}{
		{"generic", bodyProvider{strings.NewReader("raw body")}, strings.NewReader("raw body"), false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := tt.p.Body()
			if (err != nil) != tt.wantErr {
				t.Errorf("bodyProvider.Body() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("bodyProvider.Body() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestBodyProviderInterface(t *testing.T) {

	// make and configure a mocked BodyProvider
	mockedBodyProvider := &BodyProviderMock{
		BodyFunc: func() (io.Reader, error) {
			unbased, _ := base64.StdEncoding.DecodeString("data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCADeAN4DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDtKKKK/cD8rCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/Z")
			return bytes.NewReader(unbased), nil
		},
		ContentTypeFunc: func() string {
			return pngContentType
		},
	}

	m := New().Client(http.DefaultClient)
	req, _ := m.New().Base("http://example.com").BodyProvider(mockedBodyProvider).Request()
	handler := func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", mockedBodyProvider.ContentType())
		body, _ := ioutil.ReadAll(r.Body)
		w.Write(body)
	}

	w := httptest.NewRecorder()
	handler(w, req)
	resp := w.Result()


	if got := resp.Header.Get("Content-Type"); mockedBodyProvider.ContentType() != got {
		t.Errorf("BodyProvider.ContentType() = %v, want %v", got, mockedBodyProvider.ContentType())
	}

	mockedBody, _ := mockedBodyProvider.Body()
	wantBody, _ := ioutil.ReadAll(mockedBody)
	gotBody, _ := ioutil.ReadAll(resp.Body)
	if  len(gotBody) != len(wantBody) {
		t.Errorf("BodyProvider.Body() = %v, want %v", gotBody, wantBody)
	}

}
